<a href="https://colab.research.google.com/github/vanshikapanchal2710/ML-journey/blob/main/numpy/numpy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **--------NUMPY NOTES--------**

In [8]:
import numpy as np
# Basic Array creation
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


vector and matrics

In [9]:
a = [[1,2,3],[4,5,6],[7,8,9]]
print(np.array(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **Array** generation functions

In [10]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
arr2 = np.zeros((6,6))
print(arr2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [13]:
arr3 = np.zeros((4,6))
print(arr3)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [14]:
arr4 = np.ones((4,5))
print(arr4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


linspace is used to generate no. between two numbers in equal space

In [15]:
arr5 = np.linspace(1,2,10)
print(arr5)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [16]:
arr6 = np.linspace(1,5,10)
print(arr6)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


# **RANDOM** GENERATION FUNCTIONS


In [17]:
#.rand gives value between 0 and 1 only
arr7 = np.random.rand(10)
print(arr7)
# no. we give in bracket is the numbers of random no. we want

[0.19287377 0.56065729 0.16348132 0.04954681 0.35631439 0.52270295
 0.54344427 0.66161868 0.29174353 0.98375832]


In [18]:
# randn() generates samples from a standard normal distribution
arr8 = np.random.randn(2)
print(arr8)

[ 0.73574957 -0.53517101]


In [19]:
#randint is used to generate a single random no. between 0 to no. you pass in brackets
arr9 = np.random.randint(6)
print(arr9)
#randint(low point,high point,no. we want)


1


# **ARRAY** ATTRIBUTES

brackets are not used after attributes
attributes - shape,size,data type

In [20]:
arr10 = np.array([[1,2,3],[2,3,4],[4,5,7]])
arr10.shape

(3, 3)

In [21]:
arr10.size

9

In [22]:
arr10.dtype

dtype('int64')

# Array method - min,max,sum,mean,std(standard deviation),argmax,**argmin**

In [23]:
a = arr10.min()
print(a)

1


In [24]:
b = arr10.max()
print(b)

7


In [25]:
c = arr10.sum()
print(c)

31


In [26]:
# if we want row or column wise sum then we use np.sum(arr,axis) where column wise sum is done by axis =0 and row wise sum axis =1
a = np.sum(arr10,axis=0) # answer = sum columns wise
b = np.sum(arr10,axis=1)
print(a,b)

[ 7 10 14] [ 6  9 16]


In [27]:
a = arr10.mean()
print(a)

3.4444444444444446


In [28]:
a = arr10.std()
print(a)

1.7069212773041351


In [29]:
#argmax(),argmin(), gives the index of max and min number in array
a = arr10.argmax()
b = arr10.argmin()
print(a,b)

8 0


# Reshaping and **Resizing**

In [30]:
arr11 = np.arange(1,51)
print(arr11)
arr12 = arr11.reshape(10,5)
print(arr12)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


NUMPY INDEXING AND SLICING

In [31]:
arr12 = np.arange(1,31).reshape(6,5)
print(arr12)
print(arr12[3:,3:])
#arr[row start:row end , col start : col end] for slicing matrix

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[19 20]
 [24 25]
 [29 30]]


BOOLEAN INDEXING

In [32]:
arr = np.arange(11,21)
bool_index = arr % 2 == 0
print(bool_index)
arr1 = arr[bool_index]
print(arr1)

[False  True False  True False  True False  True False  True]
[12 14 16 18 20]


# ARRAY OPERATIONS



*   ARITHMETIC OPERATIONS
*   BROADCASTING
*   DEEP AND SHALLOW COPY
*   MATRIX OPERATIONS
*   ADVANCED ARRAY MANIPULATON
*   STACKING ARRAY
*   SPLITTING ARRAY








In [33]:
a1 = np.arange(1,11)
a2 = np.arange(11,21)
a1 + a2
#no. of elements in both array should be same to perform addition and this will add both array corresponding element in same index

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [34]:
print(a1)
print(a2)
print(a2-a1)
print(a1*a2)
print(a1/a2)
print(a1%a2)
print(a1 + 10) # broadcasting
#you can perform all operations

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[10 10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


DEEP AND SHALLOW COPY

shallow copy is when you slice out something from array and change in that slice would not affect the main array
and in deep copy its opposite if you change in slice it will got change in main array

In [35]:
a = np.arange(1,11)
slice = a[1:7]
print(a)
print(slice)
slice = slice*10
print(slice)
print(a)#no change in main array so shallow copy

[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6 7]
[20 30 40 50 60 70]
[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
a = np.array([1, 2, 3, 4, 5])

b = a[1:4]

b[0] = 100

print(a)
print(b)

[  1 100   3   4   5]
[100   3   4]


In [37]:
a = np.arange(1,11)
print(a)
b = a.copy()
b[0] = 27
print(a)
print(b) # this time no change in a because we use .copy()it converted into shallow copy

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[27  2  3  4  5  6  7  8  9 10]


MATRIX OPERATIONS

TO MULITIPLY A MATRIX IN NUMPY WE USE @

In [38]:
a = np.arange(1,11).reshape(2,5)
b = np.arange(11,21).reshape(5,2)
print(a @ b)
print(np.dot(a,b)) # this also give same output

[[245 260]
 [620 660]]
[[245 260]
 [620 660]]


to get transpose of a matrix we just write.T

In [39]:
a.T # capital T is necessary

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

ADVANCED ARRAY MANIPULATION


stacking array

you can't stack matrix it only done on array simple

In [40]:
#vstack = vertical stack
a = np.arange(1,6)
b = np.arange(6,11)
print(a)
print(b)
print(np.vstack((a,b)))
# this is called vertical stacking

[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
#horizontal stacking
hor = np.hstack((a,b))
print(hor)
#simply converted into 1 dimension by adding horizontally

[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
#column stack
col = np.column_stack((a,b))
col

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

splitting array

In [43]:
#hsplit means horizontal spilitiing
np.hsplit(col,2) # split col into 2

[array([[1],
        [2],
        [3],
        [4],
        [5]]),
 array([[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])]

In [44]:
np.vsplit(col,5)

[array([[1, 6]]),
 array([[2, 7]]),
 array([[3, 8]]),
 array([[4, 9]]),
 array([[ 5, 10]])]